apiVersion: v1
kind: Service
metadata:
  name: hello-application
spec:
  selector:
    app: hello-application
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-application
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-application
  strategy:
     rollingUpdate:
       maxSurge: 1
       maxUnavailable: 1%
     type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-application
    spec:
      containers:
        - name: hello-application
          image: ahmedgmansour/hello-application
          imagePullPolicy: Always
          ports:
            - name: hello-application
              containerPort: 80
          # volumeMounts:
          # - mountPath: /app/bundle/temp
          #   name: hello-application-temp
          # - mountPath: /app/bundle/logs
          #   name: hello-application-logs
          # - mountPath: /app/bundle/uploads
          #   name: hello-application-uploads

      imagePullSecrets:
      - name: regcred
      
      # volumes:
      # - name: hello-application-temp
      #   hostPath:
      #     # directory location on host
      #     path: /opt/hello-application-temp
      #     # this field is optional
      #     type: Directory
      # - name: hello-application-logs
      #   hostPath:
      #     # directory location on host
      #     path: /opt/hello-application-logs
      #     # this field is optional
      #     type: Directory
      # - name: hello-application-uploads
      #   hostPath:
      #     # directory location on host
      #     path: /opt/hello-application-uploads
      #     # this field is optional
      #     type: Directory
